# Generated by Django 3.1.7 on 2021-04-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_refreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
